"""Read and write CLAUDE_DEPS.md.

The file is meant to be committed and reviewed in a PR, so it is plain
markdown rather than a serialised blob. It has two kinds of content:

  * machine fields (`- kind:`, `- pinned:`, `- fingerprint:`) rewritten on
    every run,
  * an `### Assessment` prose block per dependency, authored by Claude and
    *preserved* across runs — that is the accumulated judgement about what
    this dependency means to this project, and regenerating it from scratch
    every time would throw away the most valuable part of the file.
"""

from __future__ import annotations

import os
import re
from datetime import date

from .model import CompanionPin, Declaration, Dep, Site, Upstream

FILENAME = "CLAUDE_DEPS.md"

HEADER_NOTE = (
    "<!-- Generated by update-tools. The `- fingerprint:` lines let /deps:sync\n"
    "     detect drift without an LLM call; do not edit them by hand.\n"
    "     Text under `### Assessment` is written by Claude and preserved across\n"
    "     runs — edit it freely, it is the point of this file. -->"
)


# ---------------------------------------------------------------- serialising


def _fmt_list(key: str, items: list[str], indent: str = "  ") -> list[str]:
    if not items:
        return []
    out = [f"- {key}:"]
    out += [f"{indent}- {it}" for it in items]
    return out


def render(deps: list[Dep], root: str, meta: dict) -> str:
    lines: list[str] = ["# Dependency profile", "", HEADER_NOTE, ""]
    lines += [
        f"- repo: {meta.get('repo', os.path.basename(os.path.abspath(root)))}",
        f"- generated: {meta.get('generated', date.today().isoformat())}",
        f"- backend: {meta.get('backend', 'builtin')}",
        f"- manifests: {', '.join(meta.get('manifests', []))}",
        f"- deps: {len(deps)}",
        "",
    ]
    if meta.get("context"):
        lines += ["## Project context", "", meta["context"].strip(), ""]

    for dep in deps:
        fp = dep.fingerprint(root)
        lines.append(f"## {dep.name}")
        lines.append("")
        lines.append(f"- kind: {dep.kind}")
        pin = dep.raw_pin or dep.version or "(unpinned)"
        lines.append(f"- pinned: {pin}" + (f" — {dep.declared_in}" if dep.declared_in else ""))
        # Only worth spelling out when there is more than one; a single
        # declaration is already the `- pinned:` line.
        if len(dep.declarations) > 1:
            lines += _fmt_list("declarations", [d.render() for d in dep.declarations])
        if dep.aliases:
            lines.append(f"- aliases: {', '.join(dep.aliases)}")
        if dep.version:
            lines.append(f"- version: {dep.version}")
        if dep.installed_version:
            lines.append(f"- installed-here: {dep.installed_version}")
        if dep.integrity:
            lines.append(f"- integrity: {dep.integrity}")
        lines.append(f"- scope: {dep.scope}")
        lines.append(f"- upstream: {dep.upstream.kind}:{dep.upstream.ref}")
        if dep.call_depth is not None:
            lines.append(f"- call-depth: {dep.call_depth}")
        if dep.blast_radius is not None:
            lines.append(f"- blast-radius: {dep.blast_radius}")
        if dep.backend:
            lines.append(f"- backend: {dep.backend}")
        lines += _fmt_list("consumed", dep.consumed)
        lines += _fmt_list("sites", [
            f"{s.path}:{s.line}" + (f" — {s.symbol}" if s.symbol else "") for s in dep.sites
        ])
        lines += _fmt_list("companion-pins", [p.render() for p in dep.companion_pins])
        lines += _fmt_list("scope-evidence", dep.scope_evidence)
        lines += _fmt_list("notes", dep.notes)
        lines.append(
            f"- fingerprint: decl={fp['decl']} sites={fp['sites']} pin={fp['pin']}"
        )
        lines.append("")
        lines.append("### Assessment")
        lines.append("")
        lines.append(dep.assessment.strip() if dep.assessment else "_not yet assessed_")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ------------------------------------------------------------------ parsing


_SECTION = re.compile(r"^## (?!Project context)(.+?)\s*$", re.M)
_FIELD = re.compile(r"^- ([a-z\-]+):\s*(.*)$", re.M)
_ITEM = re.compile(r"^\s+- (.*)$")
_SITE = re.compile(r"^(.+?):(\d+)(?:\s+—\s+(.*))?$")


def parse(text: str) -> tuple[list[Dep], dict]:
    """Return (deps, meta). Tolerant: unknown fields are ignored."""
    meta: dict = {}
    head, *rest = re.split(r"^## ", text, maxsplit=1, flags=re.M)
    for m in _FIELD.finditer(head):
        meta[m.group(1)] = m.group(2).strip()
    if "manifests" in meta:
        meta["manifests"] = [s.strip() for s in meta["manifests"].split(",") if s.strip()]

    deps: list[Dep] = []
    if not rest:
        return deps, meta

    body = "## " + rest[0]
    chunks = re.split(r"^## ", body, flags=re.M)[1:]
    for chunk in chunks:
        name, _, remainder = chunk.partition("\n")
        name = name.strip()
        if name.lower() == "project context":
            meta["context"] = remainder.strip()
            continue

        fields_part, _, assessment = remainder.partition("### Assessment")
        dep = Dep(name=name, kind="unknown")
        dep.assessment = assessment.strip()
        if dep.assessment == "_not yet assessed_":
            dep.assessment = ""

        current_list: str | None = None
        for line in fields_part.splitlines():
            fm = _FIELD.match(line)
            if fm:
                key, val = fm.group(1), fm.group(2).strip()
                current_list = key if not val else None
                _assign(dep, key, val)
                continue
            im = _ITEM.match(line)
            if im and current_list:
                _append(dep, current_list, im.group(1).strip())
        deps.append(dep)
    return deps, meta


def _assign(dep: Dep, key: str, val: str) -> None:
    if not val:
        return
    if key == "kind":
        dep.kind = val
    elif key == "pinned":
        pin, _, where = val.partition(" — ")
        dep.raw_pin = "" if pin.strip() == "(unpinned)" else pin.strip()
        dep.declared_in = where.strip()
    elif key == "version":
        dep.version = val
    elif key == "installed-here":
        dep.installed_version = val
    elif key == "integrity":
        dep.integrity = val
    elif key == "scope":
        dep.scope = val
    elif key == "upstream":
        kind, _, ref = val.partition(":")
        dep.upstream = Upstream(kind=kind.strip(), ref=ref.strip())
    elif key in ("call-depth", "blast-radius"):
        try:
            setattr(dep, key.replace("-", "_"), int(val))
        except ValueError:
            pass
    elif key == "backend":
        dep.backend = val
    elif key == "aliases":
        dep.aliases = [s.strip() for s in val.split(",") if s.strip()]
    elif key == "fingerprint":
        dep.stored_fingerprint = dict(
            re.findall(r"(\w+)=(\w+)", val)
        )


def _append(dep: Dep, key: str, item: str) -> None:
    if key == "consumed":
        dep.consumed.append(item)
    elif key == "sites":
        m = _SITE.match(item)
        if m:
            dep.sites.append(
                Site(path=m.group(1), line=int(m.group(2)), symbol=(m.group(3) or "").strip())
            )
    elif key == "declarations":
        decl = Declaration.parse(item)
        if decl:
            dep.declarations.append(decl)
    elif key == "companion-pins":
        pin = CompanionPin.parse(item)
        if pin:
            dep.companion_pins.append(pin)
    elif key == "scope-evidence":
        dep.scope_evidence.append(item)
    elif key == "notes":
        dep.notes.append(item)


# ---------------------------------------------------------------------- io


def path_for(root: str) -> str:
    return os.path.join(root, FILENAME)


def exists(root: str) -> bool:
    return os.path.isfile(path_for(root))


def load(root: str) -> tuple[list[Dep], dict]:
    if not exists(root):
        return [], {}
    return parse(open(path_for(root), encoding="utf-8", errors="replace").read())


def save(root: str, deps: list[Dep], meta: dict) -> str:
    p = path_for(root)
    with open(p, "w", encoding="utf-8") as fh:
        fh.write(render(deps, root, meta))
    return p


def carry_over(fresh: list[Dep], old: list[Dep]) -> None:
    """Preserve Claude-authored assessments when regenerating machine fields."""
    by_name = {d.name: d for d in old}
    for dep in fresh:
        prev = by_name.get(dep.name)
        if prev is not None and prev.assessment:
            dep.assessment = prev.assessment
